#!/usr/bin/env ruby

# frozen_string_literal: true

# rubocop:disable all

ENV['RAILS_ENV'] ||= 'production'

require_relative "./app"
require "anycable-rails"

Anycable.connection_factory = ActionCable.server.config.connection_class.call
Anycable.config.redis_channel = "rbmy"

Rails.application.initialize!

unless ENV['SKIP_ANYCABLE_GO']
  go_thread = Thread.new do
    Process.wait Process.spawn("anycable-go -redis_channel=rbmy")
    raise "Anycable-Go failed!"
  end

  go_thread.abort_on_exception = true
end

Anycable::Server.start
