#!/usr/bin/env ruby

# frozen_string_literal: true

# rubocop:disable all

require_relative "./app"
require "anycable-rails"

Anycable.config.connection_factory = ActionCable.server.config.connection_class.call
Anycable.config.redis_channel = "anycable"

Rails.application.eager_load!

unless ENV['SKIP_ANYCABLE_GO']
  go_thread = Thread.new do
    Process.wait Process.spawn("anycable-go -redis_channel=anycable")
    raise "Anycable-Go failed!"
  end

  go_thread.abort_on_exception = true
end

Anycable::Server.start
